### ISSUE TITLE
PhantomJS error: A service failed in the 'onPrepare' hook

### ISSUE THREAD

**Issue by renuez** [renuez/codecademy-tdd-gather-phase3#1]
```
philipp@THIN MINGW64 /c/Working/codecademy-tdd-gather-phase3 (master)
$ npm test

> pinter@0.0.0 test C:\Working\codecademy-tdd-gather-phase3
>  sh bin\mocha-test && sh bin\wdio-test



  Model: Item
    #title
      √ is a String
      √ is not empty
    #description
      √ is a String
      √ is not empty
    #imageUrl
      √ is a String
      √ is not empty

  Server path: /
    GET
GET / 200 24.896 ms - 1871
      √ renders an item with a title and image (144ms)
GET / 200 6.313 ms - 2712
      √ renders all items from the database (58ms)

  Server path: /items/create
    GET
GET /items/create 200 8.849 ms - 1914
      √ renders empty input fields
    POST
POST /items/create 302 47.021 ms - 23
      √ creates and renders a new item (54ms)
POST /items/create 302 30.552 ms - 23
      √ redirects to /
POST /items/create 400 13.010 ms - 1989
      √ displays an error message when supplied an empty title
POST /items/create 400 6.383 ms - 1995
      √ displays an error message when supplied an empty description
POST /items/create 400 3.868 ms - 1992
      √ displays an error message when supplied an empty image URL

  Server path: /items/:id
    GET
GET /items/5c11532fac7f96265843a95f 200 7.366 ms - 1276
      √ shows the title and description of the selected item (47ms)


  15 passing (633ms)

A service failed in the 'onPrepare' hook
TypeError: "file" argument must be a non-empty string
    at normalizeSpawnArguments (child_process.js:384:11)
    at exports.spawn (child_process.js:497:38)
    at exports.exec (C:\Working\codecademy-tdd-gather-phase3\node_modules\phantomjs-prebuilt\lib\phantomjs.js:72:10)
    at C:\Working\codecademy-tdd-gather-phase3\node_modules\phantomjs-prebuilt\lib\phantomjs.js:89:34
    at initializePromise (C:\Working\codecademy-tdd-gather-phase3\node_modules\phantomjs-prebuilt\node_modules\es6-promise\dist\es6-promise.js:458:5)
    at new Promise (C:\Working\codecademy-tdd-gather-phase3\node_modules\phantomjs-prebuilt\node_modules\es6-promise\dist\es6-promise.js:874:33)
    at Object.exports.run (C:\Working\codecademy-tdd-gather-phase3\node_modules\phantomjs-prebuilt\lib\phantomjs.js:87:10)
    at PhantomJSLauncher.onPrepare (C:\Working\codecademy-tdd-gather-phase3\node_modules\wdio-phantomjs-service\lib\launcher.js:21:26)
    at C:\Working\codecademy-tdd-gather-phase3\node_modules\webdriverio\build\lib\launcher.js:398:66
    at Array.map (<anonymous>)
    at Launcher._callee2$ (C:\Working\codecademy-tdd-gather-phase3\node_modules\webdriverio\build\lib\launcher.js:396:71)
    at tryCatch (C:\Working\codecademy-tdd-gather-phase3\node_modules\regenerator-runtime\runtime.js:62:40)
    at Generator.invoke [as _invoke] (C:\Working\codecademy-tdd-gather-phase3\node_modules\regenerator-runtime\runtime.js:296:22)
    at Generator.prototype.(anonymous function) [as next] (C:\Working\codecademy-tdd-gather-phase3\node_modules\regenerator-runtime\runtime.js:114:21)
    at step (C:\Working\codecademy-tdd-gather-phase3\node_modules\webdriverio\node_modules\babel-runtime\helpers\asyncToGenerator.js:17:30)
    at C:\Working\codecademy-tdd-gather-phase3\node_modules\webdriverio\node_modules\babel-runtime\helpers\asyncToGenerator.js:35:14

Continue...
ERROR: Couldn't connect to selenium server
phantomjs
Error: Couldn't connect to selenium server

ERROR: Couldn't connect to selenium server
phantomjs
Error: Couldn't connect to selenium server

ERROR: Couldn't connect to selenium server
phantomjs
Error: Couldn't connect to selenium server



==================================================================
Number of specs: 3
npm ERR! Test failed.  See above for more details.
```

**Comment by renuez** [comment]
I couldn't find the issue, therefore I used a CentOS7 VM, installed all dependencies, and the latest code without any further modifications run successful:
```
[root@localhost codecademy-tdd-gather-phase3-test]# npm test

> pinter@0.0.0 test /root/codecademy-tdd-gather-phase3-test
> bin/mocha-test && bin/wdio-test



  Model: Item
    #title
      ✓ is a String
      ✓ is not empty
    #description
      ✓ is a String
      ✓ is not empty
    #imageUrl
      ✓ is a String
      ✓ is not empty

  Server path: /
    GET
GET / 200 44.803 ms - 1871
      ✓ renders an item with a title and image (258ms)
GET / 200 34.632 ms - 2712
      ✓ renders all items from the database (99ms)

  Server path: /items/create
    GET
GET /items/create 200 23.423 ms - 1914
      ✓ renders empty input fields (74ms)
    POST
POST /items/create 302 43.469 ms - 23
      ✓ creates and renders a new item (49ms)
POST /items/create 302 22.676 ms - 23
      ✓ redirects to /
POST /items/create 400 12.902 ms - 1989
      ✓ displays an error message when supplied an empty title
POST /items/create 400 4.273 ms - 1995
      ✓ displays an error message when supplied an empty description
POST /items/create 400 3.944 ms - 1992
      ✓ displays an error message when supplied an empty image URL

  Server path: /items/:id
    GET
GET /items/5c1382688f4e1d3b4bd41fd2 200 35.936 ms - 1314
      ✓ shows the title and description of the selected item (90ms)


  15 passing (1s)

GET /items/create 200 78.562 ms - 1914
GET /stylesheets/reset.css 200 7.802 ms - 1180
GET /img/back.svg 200 7.930 ms - 1035
GET /img/logo.svg 200 8.021 ms - 1315
GET /stylesheets/style.css 200 8.037 ms - 7696
POST /items/create 302 80.492 ms - 46
GET / 200 16.948 ms - 1871
GET /stylesheets/reset.css 200 4.945 ms - 1180
GET /stylesheets/style.css 200 5.022 ms - 7696
GET /img/logo.svg 200 4.935 ms - 1315
GET /img/delete.svg 200 4.897 ms - 1361
GET /img/view.svg 200 4.553 ms - 2038
GET /img/add.svg 200 4.574 ms - 868
------------------------------------------------------------------
[phantomjs #0-0] Session ID: fb285640-ff88-11e8-9e73-7f697beeb54b
[phantomjs #0-0] Spec: /root/codecademy-tdd-gather-phase3-test/test/features/user-visits-create-test.js
[phantomjs #0-0] Running: phantomjs
[phantomjs #0-0]
[phantomjs #0-0] User visits the create page
[phantomjs #0-0]
[phantomjs #0-0] posts a new item
[phantomjs #0-0]   ✓ and is rendered
[phantomjs #0-0]
[phantomjs #0-0]
[phantomjs #0-0] 1 passing (3s)
[phantomjs #0-0]

GET / 200 42.057 ms - 1008
GET /stylesheets/reset.css 200 8.304 ms - 1180
GET /img/add.svg 200 8.719 ms - 868
GET /img/logo.svg 200 8.867 ms - 1315
GET /stylesheets/style.css 200 8.904 ms - 7696
GET / 304 61.723 ms - -
GET /stylesheets/reset.css 200 1.834 ms - 1180
GET /stylesheets/style.css 200 1.936 ms - 7696
GET /img/logo.svg 200 1.872 ms - 1315
GET /img/add.svg 200 1.876 ms - 868
GET /items/create 200 4.606 ms - 1914
GET /stylesheets/reset.css 200 4.729 ms - 1180
GET /stylesheets/style.css 200 4.643 ms - 7696
GET /img/logo.svg 200 4.752 ms - 1315
GET /img/back.svg 200 4.731 ms - 1035
------------------------------------------------------------------
[phantomjs #0-1] Session ID: fd7be330-ff88-11e8-9e73-7f697beeb54b
[phantomjs #0-1] Spec: /root/codecademy-tdd-gather-phase3-test/test/features/user-visits-root-test.js
[phantomjs #0-1] Running: phantomjs
[phantomjs #0-1]
[phantomjs #0-1] User visits root
[phantomjs #0-1]
[phantomjs #0-1] without existing items
[phantomjs #0-1]   ✓ starts blank
[phantomjs #0-1]
[phantomjs #0-1] can navigate
[phantomjs #0-1]   ✓ to the create page
[phantomjs #0-1]
[phantomjs #0-1]
[phantomjs #0-1] 2 passing (1s)
[phantomjs #0-1]

GET /items/create 304 27.980 ms - -
GET /stylesheets/reset.css 200 14.612 ms - 1180
GET /img/back.svg 200 14.860 ms - 1035
GET /img/logo.svg 200 14.764 ms - 1315
GET /stylesheets/style.css 200 14.675 ms - 7696
POST /items/create 302 71.010 ms - 46
GET / 200 14.363 ms - 1871
GET /stylesheets/reset.css 200 3.174 ms - 1180
GET /stylesheets/style.css 200 3.398 ms - 7696
GET /img/logo.svg 200 3.530 ms - 1315
GET /img/delete.svg 200 3.601 ms - 1361
GET /img/add.svg 200 3.552 ms - 868
GET /img/view.svg 200 3.579 ms - 2038
GET /items/5c138271abe8ba3ba619fcc4 200 7.396 ms - 1314
GET /stylesheets/reset.css 200 1.221 ms - 1180
GET /stylesheets/style.css 200 1.203 ms - 7696
GET /img/logo.svg 200 1.217 ms - 1315
GET /img/back.svg 200 1.231 ms - 1035
------------------------------------------------------------------
[phantomjs #0-2] Session ID: fe99d650-ff88-11e8-9e73-7f697beeb54b
[phantomjs #0-2] Spec: /root/codecademy-tdd-gather-phase3-test/test/features/user-visits-single-item-test.js
[phantomjs #0-2] Running: phantomjs
[phantomjs #0-2]
[phantomjs #0-2] User navigates to /items/:id
[phantomjs #0-2]
[phantomjs #0-2] by clicking on a created item
[phantomjs #0-2]   ✓ displays information on the item
[phantomjs #0-2]
[phantomjs #0-2]
[phantomjs #0-2] 1 passing (4s)
[phantomjs #0-2]



==================================================================
Number of specs: 3


4 passing (11.00s)

```
